services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
    - ASPNETCORE_URLS=http://+:8080
    - ASPNETCORE_HTTP_PORT=http://+:5000
    image: "engkhaledmousa/user-manager:latest"